package com.greedao.greedao_demo.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.greedao.greedao_demo.LeaderJoinEmployee;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LEADER_JOIN_EMPLOYEE".
*/
public class LeaderJoinEmployeeDao extends AbstractDao<LeaderJoinEmployee, Long> {

    public static final String TABLENAME = "LEADER_JOIN_EMPLOYEE";

    /**
     * Properties of entity LeaderJoinEmployee.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LId = new Property(1, Long.class, "lId", false, "L_ID");
        public final static Property EId = new Property(2, Long.class, "eId", false, "E_ID");
    }


    public LeaderJoinEmployeeDao(DaoConfig config) {
        super(config);
    }
    
    public LeaderJoinEmployeeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LEADER_JOIN_EMPLOYEE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"L_ID\" INTEGER," + // 1: lId
                "\"E_ID\" INTEGER);"); // 2: eId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LEADER_JOIN_EMPLOYEE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LeaderJoinEmployee entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long lId = entity.getLId();
        if (lId != null) {
            stmt.bindLong(2, lId);
        }
 
        Long eId = entity.getEId();
        if (eId != null) {
            stmt.bindLong(3, eId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LeaderJoinEmployee entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long lId = entity.getLId();
        if (lId != null) {
            stmt.bindLong(2, lId);
        }
 
        Long eId = entity.getEId();
        if (eId != null) {
            stmt.bindLong(3, eId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LeaderJoinEmployee readEntity(Cursor cursor, int offset) {
        LeaderJoinEmployee entity = new LeaderJoinEmployee( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // lId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // eId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LeaderJoinEmployee entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setEId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LeaderJoinEmployee entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LeaderJoinEmployee entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LeaderJoinEmployee entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
